### ISSUE TITLE
Won't work for me on SabNZB

### ISSUE THREAD

**Issue by D3ltorohd** [caronc/nzb-notify#17]
Hello, 

i have a problem with your notify script. I set it up like your post here. And when i test it in sabnzb he says all is fine. But when some action is on sab there are no messages but many issues. Here are some of it...

`2017-05-07 21:02:24,609	FEHLER:	Skript gab Fehlercode 1 und Ausgabe "2017-05-07 21:02:24,434 - 6244 - FEHLER: - Fatal Exception: Traceback (most recent call last): File "C:\Program Files\SABnzbd\scripts\nzbToMedia\Notify\nzbget\ScriptBase.py", line 2873, in run exit_code = main_function(*args, **kwargs) File "C:\Program Files\SABnzbd\scripts\nzbToMedia\Notify.py", line 1106, in main notify_type=notify_type, File "C:\Program Files\SABnzbd\scripts\nzbToMedia\Notify.py", line 898, in notify nobj.notify(body=body, title=title, notify_type=notify_type) File "C:\Program Files\SABnzbd\scripts\nzbToMedia\Notify\pnotify\NotifyBase.py", line 380, in notify **kwargs): File "C:\Program Files\SABnzbd\scripts\nzbToMedia\Notify\pnotify\NotifyXBMC.py", line 157, in _notify title, body, notify_type, **kwargs) File "C:\Program Files\SABnzbd\scripts\nzbToMedia\Notify\pnotify\NotifyXBMC.py", line 146, in _payload_20 return (headers, dumps(payload)) File "C:\Python27\lib\json\__init__.py", line 244, in dumps return _default_encoder.encode(obj) File "C:\Python27\lib\json\encoder.py", line 207, in encode chunks = self.iterencode(o, _one_shot=True) File "C:\Python27\lib\json\encoder.py", line 270, in iterencode return _iterencode(o, 0) UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 17: invalid start byte " zurück`

Maybe you can help me...

Greet's

**Comment by caronc** [comment]
The **ü** in **zurück** is tripping you up.  I'll try my best to add some better character encoding support for you this week if I can. In the meantime; the script should still work for you 99% of the time (obviously not for this one though).

**Comment by caronc** [comment]
When you have a chance; grab the latest version from the [master branch](https://github.com/caronc/nzb-notify/archive/master.zip) and give it another try.

**Comment by D3ltorohd** [comment]
Ok, i will test it later, and give you feedback. Thanks for your new version.

**Comment by D3ltorohd** [comment]
Sooooooory for the late respons. Now i have test it and i see the messages in kodi and on sab there i can see no errors. So i think your change works great. Many thanks for the fast support !!

**Comment by caronc** [comment]
Glad to hear! I'll close the ticket now. Feel free to open it (or another) if you have anymore​ problems.
