### ISSUE TITLE
sabnzbd notification to telegram gives an error

### ISSUE THREAD

**Issue by keppo070** [caronc/nzb-notify#34]
I setup a bot for notification. I have put the scripts in the correct folder. also the folder copied t .sabnzbd/scripts

In sabnzbd chose sabnzbd-notify in parameters tgram://<bottoken>/<chatid>

When i try test-notification an error occures

 Notification script returned exit code 1 and output "Traceback (most recent call last): File "/home/patrick/.sabnzbd/scripts/Notify.py", line 355, in <module> from pnotify import * File "/home/patrick/.sabnzbd/scripts/Notify/pnotify/__init__.py", line 26, in <module> from .NotifyBoxcar import NotifyBoxcar File "/home/patrick/.sabnzbd/scripts/Notify/pnotify/NotifyBoxcar.py", line 23, in <module> import requests File "/home/patrick/.sabnzbd/scripts/Notify/requests/__init__.py", line 53, in <module> from urllib3.contrib import pyopenssl File "/home/patrick/.sabnzbd/scripts/Notify/urllib3/contrib/pyopenssl.py", line 53, in <module> import OpenSSL.SSL File "/home/patrick/.sabnzbd/scripts/Notify/OpenSSL/__init__.py", line 8, in <module> from OpenSSL import crypto, SSL File "/home/patrick/.sabnzbd/scripts/Notify/OpenSSL/SSL.py", line 115, in <module> if _lib.Cryptography_HAS_SSL_ST: AttributeError: 'module' object has no attribute 'Cryptography_HAS_SSL_ST' "

**Comment by keppo070** [comment]
i noticed a smiliar in error in #13 
In the messages there is a comment 
pip freeze | grep -iE 'crypto|ssl'

it seems i did not have pyopenssl installed. I use pip install pyopenssl and it seems to work now.
