### ISSUE TITLE
Improve Unicode Support

### ISSUE THREAD

**Issue by caronc** [caronc/nzb-notify#49]
Here is the original [traceback source](https://forum.nzbget.net/viewtopic.php?f=8&t=1639&start=120#p20953) before it was tidied up below:
```
Traceback (most recent call last):
...
File "apprise\Apprise.py", line 248, in notify
File "path\to\markdown\__init__.py", line 470, in markdown
File "path\to\markdown\__init__.py", line 338, in convert
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 3078: ordinal not in range(128). -- Note: Markdown only accepts unicode input!
```

nzb-notify should force the conversion of all strings to unicode and not rely on apprise to do this.  Will close [apprise/20](https://github.com/caronc/apprise/issues/20) and move the issue to here instead.

**Comment by caronc** [comment]
Issue should be resolved now.
